version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - red_app

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - red_app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pacientesdb
    ports:
      - "5432:5432"
    networks:
      - red_app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - red_app

networks:
  red_app:

volumes:
  pgdata:
